### ISSUE TITLE
Update Schema Image

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/metamist#543]
Sorry for the timing... between sequencing group updates and spicy 🌶️  cohorts this is a bit of a transitional period, but can someone with a running local version of the metamist DB create an updated schema diagram for the sample-metadata repository Readme?

**Comment by nevoodoo** [comment]
Updated version: https://dbdiagram.io/d/Metamist-Schema-v6-6-2-65a48ac7ac844320aee60d16
