### ISSUE TITLE
GraphQL endpoint for Analysis by ID

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/metamist#701]
We should be able to query analyses with the GraphQL API from some given analysis ID(s). 

Primarily of interest when querying analyses by project, and would need to be updated somewhere around [this line in the schema definition](https://github.com/populationgenomics/metamist/blob/dev/api/graphql/schema.py#L179).

**Comment by nevoodoo** [comment]
Hey @EddieLF, #804 should address this issue, let me know if you're able to test and see that it helps :)
